apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: operators
spec:
  source: operatorhubio-catalog
  sourceNamespace: operators
  name: argocd-operator
  channel: <CHANNEL>  # Replace with the desired operator channel, e.g., "stable"
